### ISSUE TITLE
ΦΑΚΕΛΟΣ DOCS

### ISSUE THREAD

**Issue by SteVla82** [dalexo/AcademicManager#3]
ΜΠΟΡΕΙ ΚΑΠΟΙΟΣ ΝΑ ΑΛΛΑΞΕΙ ΤΟ AcademicManager/DOCS/DOCS/ΑΡΧΕΙΑ ΣΕ AcademicManager/DOCS/ΑΡΧΕΙΑ ?

**Comment by gmetal** [comment]
Εγινε
